#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Filla Social # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Now Available # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Make social plans with ease.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Filla LLC
your_link: https://fillasocial.com
your_city: Long Island, NY
email_address: fillasocial@gmail.com
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Plan Your Next Activity
    description: Want to avoid group chats and email chains? Invite your favorite trash talkers and ringers to fill your golf foursome without all the back & forth.
    fontawesome_icon_name: golf-ball

  - title: Fill Your Event
    description: With primary and secondary invitees; your best buds get first dibs on joining your golf match and Filla will invite your backups in case they’re unavailable.
    fontawesome_icon_name: users

  - title: Discover + Join Outings
    description: Filla will suggest events when you are free with friends you like.
    fontawesome_icon_name: calendar-alt

  - title: Get Inspired
    description: Don’t know what to do this weekend? How about this afternoon? Receive suggestions for activities based on the things you like to do and the people you like to do them with.
    fontawesome_icon_name: running

  - title: Get Connected
    description: Want to play paddle but don’t know who is available? Your Filla feed will include golf games and tennis matches hosted by your friends with open spots left.
    fontawesome_icon_name: user-friends

  - title: Handle Last minute Changes
    description: Did someone have to drop from your tennis match last minute? Filla will automatically invite attendees the host had previously invited to fill the spot

    fontawesome_icon_name: user-times

  - title: Meet New Members
    description: Display a smart app banner on iOS devices.
    fontawesome_icon_name: comments

  - title: A Calendar Full of Fun
    description: Whether you share this calendar with your wife or not, is up to you

    fontawesome_icon_name: table-tennis

  - title: Be an Ambassador
    description: Be the top social host at your club

    fontawesome_icon_name: medal

  - title: Stay in the Loop
    description: Get notified when your event is approaching and when invitees have declined or accepted their invites
    fontawesome_icon_name: bell

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/header.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
